### ISSUE TITLE
adaptive design

### ISSUE THREAD

**Issue by WisElderl** [storybrain/figma-to-html-issues#14]
### Title\
adaptive design

### Description\
![image](https://github.com/storybrain/figma-to-html-issues/assets/95701635/4c2b2096-c35d-4a50-8d41-49a25768b986)
I would like to be able to have the finished html adjust to the screen size
https://www.figma.com/file/PKF0vxzLvq91a9zQ8c938x/file?type=design&node-id=5%3A7&mode=design&t=h74UzxoDrJFomFlH-1

### Platform\
OS: Windows 10
Figma-to-HTML version: Version 22 on March 28, 2023
Browser (if applicable): Yandex

**Comment by jikkujose** [comment]
This is being planned for the pro version.
