### ISSUE TITLE
please select an artboard

### ISSUE THREAD

**Issue by trollboy** [storybrain/figma-to-html-issues#2]
### please select an artboard\
Same error as Sam B from a month ago

### Description\
No errors presented, says "Please select artboard" and never exports

### Platform\
- OS: Linux
- Figma-to-HTML version: ? Whatever figma is giving me
- Browser (if applicable): Firefox

### Additional Information\
Doesn't seem to work

**Comment by jikkujose** [comment]
Thanks! Will get back with a fix!

It would be great if it's possible to share the Figma file?
