### ISSUE TITLE
I cannot delete the project on Sandbox

### ISSUE THREAD

**Issue by ElliCharissi** [storybrain/figma-to-html-issues#5]
### Description\
By mistake we created a Sandbox of a design on Figma, just to text how this plugin works and now we cannot delete the Sandbox project/ the codebase. It seems we are not the author and we cannot change the privacy of it either

### Platform\
- OS: macOS
- Figma-to-HTML version: Version 22 on 28 March 2023 - Support for HTML/CSS
- Browser: Chrome

### Additional Information\
This is quite urgent, we need your support in order to remove the codebase from Sandbox.

**Comment by jikkujose** [comment]
You can simply delete the contents of the sandbox.
