### ISSUE TITLE
![home pagessss](https://github.com/storybrain/figma-to-html-issues/assets/135693100/70036656-6668-4e01-a78d-928641f00a66)

### ISSUE THREAD

**Issue by hanieeevk** [storybrain/figma-to-html-issues#8]
![home pagessss](https://github.com/storybrain/figma-to-html-issues/assets/135693100/70036656-6668-4e01-a78d-928641f00a66)

_Originally posted by @hanieeevk in https://github.com/storybrain/figma-to-html-issues/issues/6#issuecomment-1578086539_

**Comment by jikkujose** [comment]
Closing as the issue isn't clear.
